// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  if (license ==='none') {
    return "";
  } else {
    return`[![License: MIT](https://img.shields.io/badge/License-${license}-yellow.svg)](https://opensource.org/licenses/${license})`
  }
}
// [![License](https://img.shields.io/badge/License-${license}--Clause-blue.svg)](https://opensource.org/licenses/${license}-Clause)



// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  if (license === 'none') {
    return "";
  } else {
    return `* [License](#license)`
}
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
  if (license === 'none') {
    return "";
  } else {
    return `## License
${license}`

  }
}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data, userInfo) {
  return `# ${data.title};
${renderLicenseBadge(data.license)}
## Table of Content 
* [Description](#description)   
* [Installation](#installation) 
* [Usage](#usage) 
${renderLicenseLink(data.license)} 
* [Contributing](#contributing) 
* [Tests](#tests) 
* [Username](#username) 
* [Questions](#questions)

## Description
${data.description}
## Installation
${data.installation}
## Usage
${data.usage}
${renderLicenseSection(data.license)}
This application is covered by the ${data.license} license. 
## Contributing
${data.contributing}
## Tests
${data.tests}
## Questions

Please contact me with any questions.
![Developer Profile Picture](${userInfo.avatar_url}) 
GitHub: [${data.username}](https://github.com/${data.username})<br >
Email: ${data.email}<br />
This README was generated by [MT](https://github.com/MT0814/Week9-README-Generator-Node.js) 
`;
}

module.exports = generateMarkdown;
